local SnowmanSkins = {
    -- 雪球残影颜色
    dungball = {
        colour = {0/255, 0/255, 0/255, 0},
    },
    tumbleweed = {
        colour = {0/255, 0/255, 0/255, 0},
    },
    icecream = {
        colour = {0/255, 0/255, 0/255, 0},
    },
    invisible = {
        colour = {0/255, 0/255, 0/255, 0},
    },
    meatball = {
        colour = {0/255, 0/255, 0/255, 0},
    },
    coconut = {
        colour = {0/255, 0/255, 0/255, 0},
    },
    maodie = {
        colour = {0/255, 0/255, 0/255, 0},
    },
}

local MoreDecorations = {
    bandage_butterflywings = { canflip = true },
    bandage = { canflip = true },
    chum = { canflip = true },
    froglegs_cooked = { canflip = true },
    froglegs = { canflip = true },
    halloweencandy_10 = { canflip = true },
    halloweencandy_11 = { canflip = true },
    halloweencandy_12 = { canflip = true },
    halloweencandy_13 = { canflip = true },
    halloweencandy_14 = { canflip = true },
    halloweencandy_1 = { canflip = true },
    halloweencandy_2 = { canflip = true },
    halloweencandy_3 = { canflip = true },
    halloweencandy_4 = { canflip = true },
    halloweencandy_5 = { canflip = true },
    halloweencandy_6 = { canflip = true },
    halloweencandy_7 = { canflip = true },
    halloweencandy_8 = { canflip = true },
    halloweencandy_9 = { canflip = true },
    healingsalve_acid = { canflip = true },
    healingsalve = { canflip = true },
    mosquitomermsalve = { canflip = true },
    oceanfishingbobber_ball = { canflip = true },
    oceanfishingbobber_canary = { canflip = true },
    oceanfishingbobber_crow = { canflip = true },
    oceanfishingbobber_goose = { canflip = true },
    oceanfishingbobber_malbatross = { canflip = true },
    oceanfishingbobber_oval = { canflip = true },
    oceanfishingbobber_robin = { canflip = true },
    oceanfishingbobber_robin_winter = { canflip = true },
    oceanfishinglure_hermit_drowsy = { canflip = true },
    oceanfishinglure_hermit_heavy = { canflip = true },
    oceanfishinglure_hermit_rain = { canflip = true },
    oceanfishinglure_hermit_snow = { canflip = true },
    oceanfishinglure_spinner_blue = { canflip = true },
    oceanfishinglure_spinner_green = { canflip = true },
    oceanfishinglure_spinner_red = { canflip = true },
    oceanfishinglure_spoon_blue = { canflip = true },
    oceanfishinglure_spoon_green = { canflip = true },
    oceanfishinglure_spoon_red = { canflip = true },
    pocketwatch_dismantler = { canflip = true },
    sewing_kit = { canflip = true },
    slingshotmodkit = { canflip = true },
    slingshot_band_mimic = { canflip = true },
    slingshot_band_pigskin = { canflip = true },
    slingshot_band_tentacle = { canflip = true },
    slingshot_frame_bone = { canflip = true },
    slingshot_frame_gems = { canflip = true },
    slingshot_frame_wagpunk_0 = { canflip = true },
    slingshot_frame_wagpunk = { canflip = true },
    slingshot_handle_jelly = { canflip = true },
    slingshot_handle_silk = { canflip = true },
    slingshot_handle_sticky = { canflip = true },
    slingshot_handle_voidcloth = { canflip = true },
    tillweedsalve = { canflip = true },
    trinket_10 = { canflip = true },
    trinket_11 = { canflip = true },
    trinket_12 = { canflip = true },
    trinket_13 = { canflip = true },
    trinket_14 = { canflip = true },
    trinket_15 = { canflip = true },
    trinket_16 = { canflip = true },
    trinket_17 = { canflip = true },
    trinket_18 = { canflip = true },
    trinket_19 = { canflip = true },
    trinket_20 = { canflip = true },
    trinket_21 = { canflip = true },
    trinket_22 = { canflip = true },
    trinket_23 = { canflip = true },
    trinket_24 = { canflip = true },
    trinket_25 = { canflip = true },
    trinket_26 = { canflip = true },
    trinket_27 = { canflip = true },
    trinket_28 = { canflip = true },
    trinket_29 = { canflip = true },
    trinket_2 = { canflip = true },
    trinket_30 = { canflip = true },
    trinket_31 = { canflip = true },
    trinket_3 = { canflip = true },
    trinket_4 = { canflip = true },
    trinket_5 = { canflip = true },
    trinket_7 = { canflip = true },
    trinket_8 = { canflip = true },
    trinket_9 = { canflip = true },
    woby_treat = { canflip = true },
    spore_medium = {
        canflip = true,
        custom_animation_num_rots = 1,
        bloome_ffect = "shaders/anim.ksh",
        light = {
            falloff = 0.7,
            intensity = 0.5,
            radius = 0.5,
            colour = Vector3(196, 124, 124),
        },
    },
    spore_small = {
        canflip = true,
        custom_animation_num_rots = 1,
        bloome_ffect = "shaders/anim.ksh",
        light = {
            falloff = 0.7,
            intensity = 0.5,
            radius = 0.5,
            colour = Vector3(145, 224, 145),
        },
    },
    spore_tall = {
        canflip = true,
        custom_animation_num_rots = 1,
        bloome_ffect = "shaders/anim.ksh",
        light = {
            falloff = 0.7,
            intensity = 0.5,
            radius = 0.5,
            colour = Vector3(109, 109, 226),
        },
    },
    watermelon = { canflip = true },
    shortcake = { canflip = true },
    watermelon_cooked = { canflip = true },
    asparagus_cooked = { canflip = true },
    winter_ornament_plain1 = { canflip = true },
    winter_ornament_plain2 = { canflip = true },
    winter_ornament_plain3 = { canflip = true },
    winter_ornament_plain4 = { canflip = true },
    winter_ornament_plain5 = { canflip = true },
    winter_ornament_plain6 = { canflip = true },
    winter_ornament_plain7 = { canflip = true },
    winter_ornament_plain8 = { canflip = true },
    winter_ornament_plain9 = { canflip = true },
    winter_ornament_plain10 = { canflip = true },
    winter_ornament_plain11 = { canflip = true },
    winter_ornament_plain12 = { canflip = true },
    winter_ornament_fancy1 = { canflip = true },
    winter_ornament_fancy2 = { canflip = true },
    winter_ornament_fancy3 = { canflip = true },
    winter_ornament_fancy4 = { canflip = true },
    winter_ornament_fancy5 = { canflip = true },
    winter_ornament_fancy6 = { canflip = true },
    winter_ornament_fancy7 = { canflip = true },
    winter_ornament_fancy8 = { canflip = true },
    winter_ornament_boss_antlion = { canflip = true },
    winter_ornament_boss_bearger = { canflip = true },
    winter_ornament_boss_beequeen = { canflip = true },
    winter_ornament_boss_celestialchampion1 = { canflip = true },
    winter_ornament_boss_celestialchampion2 = { canflip = true },
    winter_ornament_boss_celestialchampion3 = { canflip = true },
    winter_ornament_boss_celestialchampion4 = { canflip = true },
    winter_ornament_boss_crabkingpearl = { canflip = true },
    winter_ornament_boss_crabking = { canflip = true },
    winter_ornament_boss_daywalker2 = { canflip = true },
    winter_ornament_boss_daywalker = { canflip = true },
    winter_ornament_boss_deerclops = { canflip = true },
    winter_ornament_boss_dragonfly = { canflip = true },
    winter_ornament_boss_eyeofterror1 = { canflip = true },
    winter_ornament_boss_eyeofterror2 = { canflip = true },
    winter_ornament_boss_fuelweaver = { canflip = true },
    winter_ornament_boss_klaus = { canflip = true },
    winter_ornament_boss_krampus = { canflip = true },
    winter_ornament_boss_malbatross = { canflip = true },
    winter_ornament_boss_minotaur = { canflip = true },
    winter_ornament_boss_moose = { canflip = true },
    winter_ornament_boss_mutatedbearger = { canflip = true },
    winter_ornament_boss_mutateddeerclops = { canflip = true },
    winter_ornament_boss_mutatedwarg = { canflip = true },
    winter_ornament_boss_noeyeblue = { canflip = true },
    winter_ornament_boss_noeyered = { canflip = true },
    winter_ornament_boss_sharkboi = { canflip = true },
    winter_ornament_boss_toadstool = { canflip = true },
    winter_ornament_boss_toadstool_misery = { canflip = true },
    winter_ornament_boss_wagstaff = { canflip = true },
    winter_ornament_boss_wormboss = { canflip = true },
    winter_ornament_shadowthralls = { canflip = true },
    winter_ornament_boss_hermithouse = { canflip = true },
    winter_ornament_boss_pearl = { canflip = true },
    winter_ornament_festivalevents1 = { canflip = true },
    winter_ornament_festivalevents2 = { canflip = true },
    winter_ornament_festivalevents3 = { canflip = true },
    winter_ornament_festivalevents4 = { canflip = true },
    winter_ornament_festivalevents5 = { canflip = true },
    winter_food1 = { canflip = true },
    winter_food2 = { canflip = true },
    winter_food3 = { canflip = true },
    winter_food4 = { canflip = true },
    winter_food5 = { canflip = true },
    winter_food6 = { canflip = true },
    winter_food7 = { canflip = true },
    winter_food8 = { canflip = true },
    winter_food9 = { canflip = true },
    halloween_ornament_1 = { canflip = true },
    halloween_ornament_2 = { canflip = true },
    halloween_ornament_3 = { canflip = true },
    halloween_ornament_4 = { canflip = true },
    halloween_ornament_5 = { canflip = true },
    halloween_ornament_6 = { canflip = true },
    bearger_fur = { canflip = true },
    blackflag = { canflip = true },
    bluegem = { canflip = true },
    bluemooneye = { canflip = true },
    blue_cap_cooked = { canflip = true },
    cactus_flower = { canflip = true },
    cactus_meat_cooked = { canflip = true },
    cactus_meat = { canflip = true },
    cave_banana_cooked = { canflip = true },
    cave_banana = { canflip = true },
    cutlichen = { canflip = true },
    cutstone = { canflip = true },
    elixir_container = { canflip = true },
    gnarwail_horn = { canflip = true },
    greengem = { canflip = true },
    greenmooneye = { canflip = true },
    green_cap_cooked = { canflip = true },
    lucky_goldnugget = { canflip = true },
    malbatross_beak = { canflip = true },
    malbatross_feathered_weave = { canflip = true },
    moonbutterflywings = { canflip = true },
    moon_tree_blossom = { canflip = true },
    opalpreciousgem = { canflip = true },
    orangegem = { canflip = true },
    orangemooneye = { canflip = true },
    palmcone_scale = { canflip = true },
    palmcone_seed = { canflip = true },
    pinecone = { canflip = true },
    pocketwatch_parts = { canflip = true },
    purplegem = { canflip = true },
    purplemooneye = { canflip = true },
    redgem = { canflip = true },
    redmooneye = { canflip = true },
    red_cap_cooked = { canflip = true },
    rock_avocado_fruit = { canflip = true },
    rock_avocado_fruit_ripe = { canflip = true },
    rock_avocado_fruit_ripe_cooked = { canflip = true },
    rock_avocado_fruit_sprout = { canflip = true },
    saltrock = { canflip = true },
    stinger = { canflip = true },
    townportaltalisman = { canflip = true },
    yellowgem = { canflip = true },
    yellowmooneye = { canflip = true },
    barnacle_cooked = { canflip = true },
    barnacle = { canflip = true },
    berries_cooked = { canflip = true },
    berries_juicy_cooked = { canflip = true },
    fig_cooked = { canflip = true },
    fig = { canflip = true },
    firenettles = { canflip = true },
    forgetmelots = { canflip = true },
    milkywhites = { canflip = true },
    minotaurhorn = { canflip = true },
    mosquitosack = { canflip = true },
    scandata = { canflip = true },
    tillweed = { canflip = true },
    transistor = { canflip = true },
    trinket_6 = { canflip = true },
    waterballoon = { canflip = true },
    wormlight_lesser = { canflip = true },
    mutator_dropper = { canflip = true },
    mutator_healer = { canflip = true },
    mutator_hider = { canflip = true },
    mutator_moon = { canflip = true },
    mutator_spitter = { canflip = true },
    mutator_warrior = { canflip = true },
    mutator_water = { canflip = true },
    papyrus = { canflip = true },
    pigskin = { canflip = true },
    rope = { canflip = true },
    silk = { canflip = true },
    spiderden_bedazzler = { canflip = true },
    spidereggsack = { canflip = true },
    spidergland = { canflip = true },
    spider_healer_item = { canflip = true },
    spider_repellent = { canflip = true },
    spider_whistle = { canflip = true },
    batwing_cooked = { canflip = true },
    boards = { canflip = true },
    cookedmandrake = { canflip = true },
    cookedmeat = { canflip = true },
    cookedmonstermeat = { canflip = true },
    cookedsmallmeat = { canflip = true },
    coontail = { canflip = true },
    crumbs = { canflip = true },
    dragon_scales = { canflip = true },
    drumstick_cooked = { canflip = true },
    drumstick = { canflip = true },
    fishmeat_cooked = { canflip = true },
    foliage = { canflip = true },
    honeycomb = { canflip = true },
    livinglog = { canflip = true },
    log = { canflip = true },
    lunarplant_husk = { canflip = true },
    mandrake = { canflip = true },
    meat = { canflip = true },
    messagebottleempty = { canflip = true },
    monstermeat = { canflip = true },
    moon_cap_cooked = { canflip = true },
    moon_cap = { canflip = true },
    plantmeat_cooked = { canflip = true },
    plantmeat = { canflip = true },
    reviver = { canflip = true },
    smallmeat = { canflip = true },
    waxpaper = { canflip = true },
    acorn_cooked = { canflip = true },
    acorn = { canflip = true },
    batnose_cooked = { canflip = true },
    slingshotammo_dreadstone = { canflip = true },
    slingshotammo_freeze = { canflip = true },
    slingshotammo_gelblob = { canflip = true },
    slingshotammo_gold = { canflip = true },
    slingshotammo_gunpowder = { canflip = true },
    slingshotammo_honey = { canflip = true },
    slingshotammo_lunarplanthusk = { canflip = true },
    slingshotammo_marble = { canflip = true },
    slingshotammo_moonglass = { canflip = true },
    slingshotammo_poop = { canflip = true },
    slingshotammo_rock = { canflip = true },
    slingshotammo_slow = { canflip = true },
    slingshotammo_stinger = { canflip = true },
    slingshotammo_thulecite = { canflip = true },
    trinket_1 = { canflip = true },
    trunk_cooked = { canflip = true },
    trunk_summer = { canflip = true },
    trunk_winter = { canflip = true },
    batnose = { canflip = true },
    beefalowool = { canflip = true },
    beeswax = { canflip = true },
    bird_egg_cooked = { canflip = true },
    bird_egg = { canflip = true },
    butterflywings = { canflip = true },
    carnival_prizeticket = { canflip = true },
    carrot_cooked = { canflip = true },
    compostwrap = { canflip = true },
    compost = { canflip = true },
    cookiecuttershell = { canflip = true },
    corn_cooked = { canflip = true },
    corn = { canflip = true },
    cutreeds = { canflip = true },
    dragonfruit_cooked = { canflip = true },
    dragonfruit = { canflip = true },
    dreadstone = { canflip = true },
    driftwood_log = { canflip = true },
    durian_cooked = { canflip = true },
    durian = { canflip = true },
    eel = { canflip = true },
    ancientfruit_nightvision_cooked = { canflip = true },
    pondeel = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    eggplant_cooked = { canflip = true },
    fertilizer = { canflip = true },
    fishmeat = { canflip = true },
    furtuft = { canflip = true },
    garlic_cooked = { canflip = true },
    garlic = { canflip = true },
    gelblob_bottle = { canflip = true },
    glommerfuel = { canflip = true },
    glommerwings = { canflip = true },
    goatmilk = { canflip = true },
    guano = { canflip = true },
    gunpowder = { canflip = true },
    honey = { canflip = true },
    horn = { canflip = true },
    kelp_cooked = { canflip = true },
    kelp = { canflip = true },
    kelp_dried = { canflip = true },
    lavae_cocoon = { canflip = true },
    lightninggoathorn = { canflip = true },
    meat_dried = { canflip = true },
    messagebottle = { canflip = true },
    monstermeat_dried = { canflip = true },
    mosquitofertilizer = { canflip = true },
    nightmare_timepiece = { canflip = true },
    onion_cooked = { canflip = true },
    onion = { canflip = true },
    pepper_cooked = { canflip = true },
    phlegm = { canflip = true },
    pomegranate_cooked = { canflip = true },
    pomegranate = { canflip = true },
    giftwrap = { canflip = true },
    battlesong_durability = { canflip = true },
    battlesong_fireresistance = { canflip = true },
    battlesong_healthgain = { canflip = true },
    battlesong_instant_panic = { canflip = true },
    battlesong_instant_revive = { canflip = true },
    battlesong_instant_taunt = { canflip = true },
    battlesong_lunaraligned = { canflip = true },
    battlesong_sanityaura = { canflip = true },
    battlesong_sanitygain = { canflip = true },
    battlesong_shadowaligned = { canflip = true },
    bedroll_straw = { canflip = true },
    bedroll_furry = { canflip = true },
    book_bees = { canflip = true },
    book_birds = { canflip = true },
    book_brimstone = { canflip = true },
    book_fire = { canflip = true },
    book_fish = { canflip = true },
    book_horticulture = { canflip = true },
    book_horticulture_upgraded = { canflip = true },
    book_light = { canflip = true },
    book_light_upgraded = { canflip = true },
    book_moon = { canflip = true },
    book_rain = { canflip = true },
    book_research_station = { canflip = true },
    book_silviculture = { canflip = true },
    book_sleep = { canflip = true },
    book_temperature = { canflip = true },
    book_tentacles = { canflip = true },
    book_web = { canflip = true },
    waxwelljournal = { canflip = true },
    poop = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    potato_cooked = { canflip = true },
    potato = { canflip = true },
    pumpkin_cooked = { canflip = true },
    pumpkin = { canflip = true },
    rottenegg = { canflip = true },
    royal_jelly = { canflip = true },
    sewing_tape = { canflip = true },
    shroom_skin = { canflip = true },
    slurper_peltd = { canflip = true },
    slurtleslime = { canflip = true },
    smallmeat_dried = { canflip = true },
    soil_amender = { canflip = true },
    soil_amender_fermented = { canflip = true },
    spoiled_fish = { canflip = true },
    spoiled_fish_small = { canflip = true },
    spoiled_food = { canflip = true },
    steelwool = { canflip = true },
    succulent_picked = { canflip = true },
    tentaclespots = { canflip = true },
    thulecite = { canflip = true },
    thulecite_pieces = { canflip = true },
    tomato_cooked = { canflip = true },
    tomato = { canflip = true },
    treegrowthsolution = { canflip = true },
    voidcloth = { canflip = true },
    wagpunk_bits = { canflip = true },
    walrus_tusk = { canflip = true },
    wetgoop = { canflip = true },
    wormlight = { canflip = true },
    wx78module_bee = { canflip = true },
    wx78module_cold = { canflip = true },
    wx78module_heat = { canflip = true },
    wx78module_light = { canflip = true },
    wx78module_maxhealth2 = { canflip = true },
    wx78module_maxhealth = { canflip = true },
    wx78module_maxhunger1 = { canflip = true },
    wx78module_maxhunger = { canflip = true },
    wx78module_maxsanity1 = { canflip = true },
    wx78module_maxsanity = { canflip = true },
    wx78module_movespeed2 = { canflip = true },
    wx78module_movespeed = { canflip = true },
    wx78module_music = { canflip = true },
    wx78module_nightvision = { canflip = true },
    wx78module_taser = { canflip = true },
    spear = { canflip = true },
    wintersfeastfuel = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    graveurn = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    ghostlyelixir_attack = { canflip = true },
    ghostlyelixir_fastregen = { canflip = true },
    ghostlyelixir_lunar = { canflip = true },
    ghostlyelixir_retaliation = { canflip = true },
    ghostlyelixir_revive = { canflip = true },
    ghostlyelixir_shadow = { canflip = true },
    ghostlyelixir_shield = { canflip = true },
    ghostlyelixir_slowregen = { canflip = true },
    ghostlyelixir_speed = { canflip = true },
    alterguardianhatshard = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    ghostflower = {
        canflip = true,
        bloome_ffect = "shaders/anim.ksh",
        custom_animation_num_rots = 16,
        fn = function(inst)
            if not TheWorld.ismastersim or inst.dofx then
                return
            end

            inst.dofx = function(inst)
                local fx = SpawnPrefab("ghostflower_spirit" .. tostring(math.random(2)) .. "_fx")
                fx.entity:SetParent(inst.entity)
                fx.Transform:SetPosition(0, 0, 0)
                inst:DoTaskInTime(3 + math.random()*6, inst.dofx) -- the min delay needs to be greater than the grow animation + it's delay
            end
            inst:dofx()
            inst.AnimState:SetFrame(math.random(inst.AnimState:GetCurrentAnimationNumFrames()) - 1)
        end
    },
    moonglass_charged = {
        canflip = true,
        bloome_ffect = "shaders/anim.ksh",
        light = {
            falloff = 0.7,
            intensity = 0.5,
            radius = 0.5,
            colour = Vector3(111, 111, 227),
        },
    },
    moonstorm_spark = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    security_pulse_cage = { canflip = true },
    security_pulse_cage_full = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    fireflies = {
        canflip = false,
        custom_animation_num_rots = 1,
        bloome_ffect = "shaders/anim.ksh",
        light = {
            falloff = 0.7,
            intensity = 0.5,
            radius = 0.5,
            colour = Vector3(180, 195, 150),
        },
    },
    mosquito = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    killerbee = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    bee = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    moonbutterfly = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    butterfly = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    compass = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    pondfish = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    singingshell_octave3 = {
        canflip = true,
        bank = "singingshell_octave_decoration",
    },
    singingshell_octave4 = {
        canflip = true,
        bank = "singingshell_octave_decoration",
    },
    singingshell_octave5 = {
        canflip = true,
        bank = "singingshell_octave_decoration",
    },
    lightbulb = {
        canflip = true,
        bloome_ffect = "shaders/anim.ksh",
        light = {
            falloff = 0.7,
            intensity = 0.5,
            radius = 0.5,
            colour = Vector3(237, 237, 209),
        },
    },
    shadowheart = { canflip = true },
    shadowheart_infused = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    nightmarefuel = {
        canflip = true,
        custom_animation_num_rots = 16,
        use_point_filtering = true,
        mult_colour = { 1, 1, 1, 0.5 },
    },
    horrorfuel = {
        canflip = true,
        custom_animation_num_rots = 16,
        use_point_filtering = true,
        mult_colour = { 1, 1, 1, 0.5 },
        anim = "shell",
        fn = function(inst, itemdata, flip, rot, isinfrontend)
            local animation = "core" .. (flip and itemdata.canflip and "_flip_" or "_") .. (rot - 1)
            if inst.core then
                inst.core.AnimState:PlayAnimation(animation, true)
                return
            end

            if TheWorld.ismastersim and not isinfrontend then
                inst.core = SpawnPrefab("horrorfuel_core_fx")
            else
                inst.core = CreateEntity()
                inst.core.persists = false
                if isinfrontend then
                    inst.core.entity:AddUITransform()
                else
                    inst.core.entity:AddTransform()
                end
                inst.core.entity:AddAnimState()
                inst.core.AnimState:SetBank(itemdata.bank)
                inst.core.AnimState:SetBuild(itemdata.build)
                inst.core.AnimState:SetFinalOffset(1)
            end

            inst.core.AnimState:PlayAnimation(animation, true)
            inst.core.AnimState:SetFrame(math.random(inst.core.AnimState:GetCurrentAnimationNumFrames()) - 1)

            inst.highlightchildren = { inst.core }
            inst.core.entity:SetParent(inst.entity)

            inst.AnimState:SetFrame(math.random(inst.AnimState:GetCurrentAnimationNumFrames()) - 1)
        end
    },
    purebrilliance = {
        canflip = true,
        custom_animation_num_rots = 16,
        use_point_filtering = true,
        bloome_ffect = "shaders/anim.ksh",
        fn = function(inst)
            inst.AnimState:SetSymbolLightOverride("pb_energy_loop", .5)
            inst.AnimState:SetSymbolLightOverride("pb_ray", .5)
            inst.AnimState:SetSymbolLightOverride("SparkleBit", .5)
            inst.AnimState:SetLightOverride(.1)
        end
    },
    slingshotammo_horrorfuel = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    slingshotammo_scrapfeather = {
        canflip = true,
        custom_animation_num_rots = 16,
    },
    slingshotammo_purebrilliance = {
        canflip = true,
        custom_animation_num_rots = 16,
        use_point_filtering = true,
        bloome_ffect = "shaders/anim.ksh",
        fn = function(inst)
            inst.AnimState:SetSymbolLightOverride("pb_energy_loop", .5)
            inst.AnimState:SetSymbolLightOverride("pb_ray", .5)
            inst.AnimState:SetSymbolLightOverride("SparkleBit", .5)
            inst.AnimState:SetLightOverride(.1)
        end
    },
    ancientfruit_gem = { canflip = true },
    ancienttree_gem_sapling_item = { canflip = true },
    ancienttree_nightvision_sapling_item = { canflip = true },
    ancienttree_seed = { canflip = true },
    antliontrinket = { canflip = true },
    archive_lockbox = { canflip = true },
    boat_bumper_crabking_kit = { canflip = true },
    boat_bumper_kelp_kit = { canflip = true },
    boat_bumper_shell_kit = { canflip = true },
    boat_bumper_yotd_kit = { canflip = true },
    carnivaldecor_banner_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
     },
    carnivaldecor_eggride1_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
     },
    carnivaldecor_eggride2_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
     },
    carnivaldecor_eggride3_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
     },
    carnivaldecor_eggride4_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
     },
    carnivaldecor_lamp_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
            light = {
                falloff = 0.7,
                intensity = 0.5,
                radius = 3,
                colour = Vector3(237, 237, 209),
            },
     },
    carnivaldecor_plant_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
     },
    carnivalfood_corntea = { canflip = true },
    carnivalgame_feedchicks_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
     },
    carnivalgame_herding_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
            light = {
                falloff = 0.7,
                intensity = 0.5,
                radius = 5,
                colour = Vector3(237, 237, 209),
            },
     },
    carnivalgame_memory_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
            light = {
                falloff = 0.7,
                intensity = 0.5,
                radius = 5,
                colour = Vector3(237, 237, 209),
            },
     },
    carnivalgame_puckdrop_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
            light = {
                falloff = 0.7,
                intensity = 0.5,
                radius = 5,
                colour = Vector3(237, 237, 209),
            },
     },
    carnivalgame_shooting_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
            light = {
                falloff = 0.7,
                intensity = 0.5,
                radius = 5,
                colour = Vector3(237, 237, 209),
            },
     },
    carnivalgame_wheelspin_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
            light = {
                falloff = 0.7,
                intensity = 0.5,
                radius = 5,
                colour = Vector3(237, 237, 209),
            },
     },
    carnival_prizebooth_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
     },
    carnivalcannon_confetti_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
     },
    carnivalcannon_sparkle_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
     },
    carnivalcannon_streamer_kit = {
            canflip = false,
            custom_animation_num_rots = 1,
     },
    carnival_gametoken = { canflip = true },
    carnival_seedpacket = { canflip = true },
    carnival_vest_a = { canflip = true },
    carnival_vest_b = { canflip = true },
    carnival_vest_c = { canflip = true },
    cotl_trinket = { canflip = true },
    deer_antler1 = { canflip = true },
    deer_antler2 = { canflip = true },
    deer_antler3 = { canflip = true },
    dug_bananabush = { canflip = true },
    dug_berrybush2 = { canflip = true },
    dug_berrybush = { canflip = true },
    dug_berrybush_juicy = { canflip = true },
    dug_grass = { canflip = true },
    dug_marsh_bush = { canflip = true },
    dug_monkeytail = { canflip = true },
    dug_rock_avocado_bush = { canflip = true },
    dug_sapling = { canflip = true },
    dug_sapling_moon = { canflip = true },
    dug_trap_starfish = { canflip = true },
    firenettles_dried = { canflip = true },
    foliage_dried = { canflip = true },
    forgetmelots_dried = { canflip = true },
    fossil_piece = { canflip = true },
    halloweenpotion_bravery_large = { canflip = true },
    halloweenpotion_bravery_small = { canflip = true },
    halloweenpotion_embers = { canflip = true },
    halloweenpotion_health_large = { canflip = true },
    halloweenpotion_health_small = { canflip = true },
    halloweenpotion_moon = { canflip = true },
    halloweenpotion_sanity_large = { canflip = true },
    halloweenpotion_sanity_small = { canflip = true },
    halloweenpotion_sparks = { canflip = true },
    hermit_cracked_pearl = { canflip = true },
    hermit_pearl = { canflip = true },
    lavae_egg = { canflip = true },
    livingtree_root = { canflip = true },
    carnivaldecor_figure_kit = { canflip = true },
    carnivaldecor_figure_kit_season2 = { canflip = true },
    lunar_seed = {
        canflip = true,
        custom_animation_num_rots = 16,
        use_point_filtering = true,
        bloome_ffect = "shaders/anim.ksh",
        fn = function(inst)
            inst.AnimState:SetSymbolLightOverride("pb_energy_loop", .5)
            inst.AnimState:SetSymbolLightOverride("pb_ray", .5)
            inst.AnimState:SetSymbolLightOverride("SparkleBit", .5)
            inst.AnimState:SetLightOverride(.1)
        end
    },
    lureplantbulb = { canflip = true },
    megaflare = { canflip = true },
    miniflare = { canflip = true },
    moon_tree_blossom_dried = { canflip = true },
    petals_dried = { canflip = true },
    petals_evil_dried = { canflip = true },
    pig_coin = { canflip = true },
    pig_token = { canflip = true },
    slurtle_shellpieces = { canflip = true },
    stash_map = { canflip = true },
    succulent_picked_dried = { canflip = true },
    tillweed_dried = { canflip = true },
    trinket_32 = { canflip = true },
    trinket_33 = { canflip = true },
    trinket_34 = { canflip = true },
    trinket_35 = { canflip = true },
    trinket_36 = { canflip = true },
    trinket_37 = { canflip = true },
    trinket_38 = { canflip = true },
    trinket_39 = { canflip = true },
    trinket_40 = { canflip = true },
    trinket_41 = { canflip = true },
    trinket_42 = { canflip = true },
    trinket_43 = { canflip = true },
    trinket_44 = { canflip = true },
    trinket_45 = { canflip = true },
    trinket_46 = { canflip = true },
    twiggy_nut = { canflip = true },
    waterplant_planter = { canflip = true },
    yotc_seedpacket = { canflip = true },
    yotc_seedpacket_rare = { canflip = true },
}

local winter_ornament_light_colours = {
    Vector3(255, 25.5, 25.5),
    Vector3(25.5, 255, 25.5),
    Vector3(127.5, 127.5, 255),
    Vector3(255, 255, 255),
    Vector3(255, 25.5, 25.5),
    Vector3(25.5, 255, 25.5),
    Vector3(127.5, 127.5, 255),
    Vector3(255, 255, 255),
}

local function winter_ornament_light_flash(inst, itemdata)
    inst.AnimState:OverrideSymbol("item", itemdata.build, "light_on")
    if not TheWorld.ismastersim then
        return
    end
    inst:DoPeriodicTask(1.2, function()
        local light = not inst.Light:IsEnabled()
        inst.AnimState:OverrideSymbol("item", itemdata.build, "light_" .. (light and "on" or "off"))
        inst.Light:Enable(light)
    end)
end

for i, colour in ipairs(winter_ornament_light_colours) do
    MoreDecorations["winter_ornament_light" .. i] = {
        canflip = true,
        bloome_ffect = "shaders/anim.ksh",
        light = {
            falloff = 0.7,
            intensity = 0.5,
            radius = 0.5,
            colour = colour,
        },
        fn = winter_ornament_light_flash
    }
end

return {
    SnowmanSkins = SnowmanSkins,
    MoreDecorations = MoreDecorations,
}
